// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // This installed version of @prisma/config's Datasource type has no
    // `directUrl` field — migrate already works fine against Neon's pooled
    // endpoint, so DATABASE_URL covers both CLI and runtime here.
    // DIRECT_URL stays in .env for any tooling that wants an unpooled
    // connection directly.
    url: env("DATABASE_URL"),
  },
});
